version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
    groups:
      minor-updates:
        applies-to: version-updates
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "13:00"
    open-pull-requests-limit: 10